---
Users:  # Users of Debile
    - name: Lucas Kanashiro
      email: kanashiro.duarte@gmail.com
      pgp: 8ED6C3F8BAC9DB7FC130A870F823A2729883C97C

Builders:  # Machines that can build
    - name: debile-slave
      maintainer: kanashiro.duarte@gmail.com
      pgp: D88A8FD511C60A566C87371E8CF4B7B89B4ED267
      ip: 172.17.0.128

Suites:
    - name: unstable

Components:
    - name: main

Arches:
    - name: amd64

Checks:
    - name: lintian
      source: true
      binary: true
      build: false

Groups:
    - name: default
      maintainer: kanashiro.duarte@gmail.com

      suites:
          - suite: unstable
            components:
                - main
            arches:
                - amd64
            checks:
                - lintian
